repos:
  primary: "."

export.auto: false
sync.remote: "https://doltremoteapi.dolthub.com/opselite/pacto-bot-api"
federation.remote: "https://doltremoteapi.dolthub.com/opselite/pacto-bot-api"


routing.contributor: .